### ISSUE TITLE
Currentcy description and screenshots at addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by grahamperrin** [tehw0lf/currentcy#1]
From the words alone at https://addons.mozilla.org/addon/currentcy/ a potential user can't guess what's done by the extension. 

Does it add a contextual menu item, to work with a selected cost? And so on. 

Screenshots will help. 

Thanks

**Comment by tehw0lf** [comment]
Thanks for the feedback, I have now added a screenshot to the listing.

What happens is that the extension uses a tree walker to traverse the DOM, using regular expressions to detect prices. In case of a successful match, it will append the converted price to the current node value and update it.

**Comment by grahamperrin** [comment]
Thanks :+1:
